-- VaultSignal v19 Signal Alert Engine
-- Production smart push routing for Signal Network.

create extension if not exists pg_net with schema extensions;

alter table public.notification_preferences
  add column if not exists watch_terms text[] not null default '{}'::text[],
  add column if not exists local_region_only boolean not null default true;

create table if not exists public.signal_push_deliveries (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.signal_posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  subscription_id uuid not null references public.push_subscriptions(id) on delete cascade,
  signal_score integer not null default 0 check (signal_score between 0 and 100),
  status text not null default 'sent' check (status in ('sent','failed','expired','skipped')),
  created_at timestamptz not null default now(),
  unique(post_id, subscription_id)
);
create index if not exists signal_push_deliveries_user_created_idx on public.signal_push_deliveries(user_id, created_at desc);
create index if not exists signal_push_deliveries_post_idx on public.signal_push_deliveries(post_id);
alter table public.signal_push_deliveries enable row level security;

drop policy if exists "service role manages signal push deliveries" on public.signal_push_deliveries;
create policy "service role manages signal push deliveries"
on public.signal_push_deliveries
for all
to service_role
using (true)
with check (true);

-- Server-only helper. The Edge Function calls this using the service role.
create or replace function public.vaultsignal_push_config()
returns jsonb
language sql
security definer
set search_path = public, vault
as $$
  select jsonb_build_object(
    'vapid_public', (select decrypted_secret from vault.decrypted_secrets where name='vaultsignal_vapid_public' limit 1),
    'vapid_private', (select decrypted_secret from vault.decrypted_secrets where name='vaultsignal_vapid_private' limit 1),
    'vapid_subject', coalesce((select decrypted_secret from vault.decrypted_secrets where name='vaultsignal_vapid_subject' limit 1),'https://2genrips.github.io/2gen-vault/'),
    'webhook_secret', (select decrypted_secret from vault.decrypted_secrets where name='vaultsignal_signal_push_webhook_secret' limit 1)
  );
$$;
revoke all on function public.vaultsignal_push_config() from public, anon, authenticated;
grant execute on function public.vaultsignal_push_config() to service_role;

-- Trigger sender. The webhook secret is decrypted only inside Postgres at call time.
create or replace function public.dispatch_vaultsignal_push()
returns trigger
language plpgsql
security definer
set search_path = public, vault, extensions
as $$
declare
  push_secret text;
  request_id bigint;
begin
  if coalesce(new.is_removed,false) then return new; end if;

  select decrypted_secret into push_secret
  from vault.decrypted_secrets
  where name='vaultsignal_signal_push_webhook_secret'
  limit 1;

  if coalesce(push_secret,'') = '' then return new; end if;

  select net.http_post(
    url := 'https://ztesewpipghbkvtbidry.supabase.co/functions/v1/signal-push',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'x-vaultsignal-secret',push_secret
    ),
    body := jsonb_build_object('record',to_jsonb(new)),
    timeout_milliseconds := 5000
  ) into request_id;

  return new;
end;
$$;
revoke all on function public.dispatch_vaultsignal_push() from public, anon, authenticated;

drop trigger if exists vaultsignal_signal_push_after_insert on public.signal_posts;
create trigger vaultsignal_signal_push_after_insert
after insert on public.signal_posts
for each row execute function public.dispatch_vaultsignal_push();

-- Authenticated clients cannot read or write the delivery audit. The explicit service-role policy
-- keeps the table clearly server-only while avoiding ambiguous RLS configuration.
